apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: misc
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Drew's Cool Shit
    theme: dark
    color: cyan
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Media:
        - Jellyfin:
            - abbr: Jellyfin
              href: https://jellyfin.${DOMAIN}
  services.yaml: ""
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: google
        target: _blank
  docker.yaml: ""
