---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: homepage-secrets
  namespace: misc
spec:
  encryptedData:
    jellyfin_api_key: AgBpBYvPhGrBN8mgHALjUxyI9ILBb6ASQQz3JkMmm76TZzUzsHL7kEWdPxtyZT70LLBLczsX8m6LeGf4nD4JBEGQmZNYqnupXS8G3gUTKOXpRUg2E73lWi3ZgDfxgcb1a4kS/EN/zNGWKFbGORFaQV7Rt9if/19mEhWxHPnyg8M8F32vEDqOon+nt7zLGnTUuBluSXqBBiZY9kGSSc38RknNVXmfQHGbkg5FNsslXxJUOshdv0AfKS4mJGTJPu9GTi0FXJQVPrXvIPlOxgjBKbw7ro5xyMBUbitJIg6Yfl75CMFqsotIX3lU9C3N1JG7QP9WiyBGbSkIikwsNxnWX9zes7Bwawr7DhJELJdiwFnPkfG0t84MnwUZr45Y4o9HaUQuqfENoLBJA0UFUSTrXvUz9AD8v9ITtCd63D0MHGlqt0mRmOO1x+2tP/rejnmJz9xBe2L5HfBa3SgvJhILVjhVUHPAyJmBhAetcPfBq9iI5pC2QD3XeOPPaEo0z2khfPSBvaPCMtp7IDtSdW3V6YTXnEQrA/U7J29U9vwZQ+aPxaIKQimMGNHHbKjUCsZyxBsF3bruD9/VpqeqV09V7E3EyTJbgrKlt5PKPX0zHCeP6oXbp7nlReMWHI6eXZgzGzCDQoh4V8A0UzBz4evaIgMObSZHGRl3F7EJm5NYjDLlXksd2oMECf0dt4xrP7+y0M1DU7T2XZIFNysL6tqR+4s3x11LQwCZ0t7gYCOwv/5KjA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: homepage-secrets
      namespace: misc
    type: Opaque
