apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: misc
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Media:
        - Jellyfin:
            - abbr: Jellyfin
              href: https://jellyfin.${DOMAIN}
        - Jellyseerr:
            - abbr: Jellyseerr
              href: https://jellyseerr.${DOMAIN}
        - Lidarr:
            - abbr: Lidarr
              href: https://lidarr.${DOMAIN}
        - Sonarr:
            - abbr: Sonarr
              href: https://sonarr.${DOMAIN}
        - Radarr:
            - abbr: Radarr
              href: https://radarr.${DOMAIN}
    - Monitoring:
        - Grafana:
            - abbr: Grafana
              href: https://grafana.${DOMAIN}
        - InfluxDB:
            - abbr: InfluxDB
              href: https://influxdb.${DOMAIN}
    - Development:
        - Jenkins:
            - abbr: Jenkins
              href: https://jenkins.${DOMAIN}
        - Github:
            - abbr: Github
              href: https://github.com/home-kops
  services.yaml: |
    - Media:
      - Jellyfin:
          icon: jellyfin.png
          href: https://jellyfin.${DOMAIN}
          description: Watch movies and TV shows.
          server: ${DOMAIN}
          container: jellyfin
          widgets:
            type: jellyfin
            url: https://jellyfin.${DOMAIN}
            key: ${JELLYFIN_API_KEY}
            enableBlocks: true
            enableNowPlaying: true
            enableUser: true
            showEpisodeNumber: true
            expandOneStreamToTwoRows: false
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: google
        target: _blank
  docker.yaml: ""
