apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: misc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - image: ghcr.io/gethomepage/homepage:v1
        name: homepage
        imagePullPolicy: IfNotPresent
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        ports:
        - containerPort: 3000
          name: web
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /app/config/custom.js
          subPath: custom.js
        - name: config
          mountPath: /app/config/custom.css
          subPath: custom.css
        - name: config
          mountPath: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
        - name: config
          mountPath: /app/config/docker.yaml
          subPath: docker.yaml
        - name: config
          mountPath: /app/config/kubernetes.yaml
          subPath: kubernetes.yaml
        - name: config
          mountPath: /app/config/services.yaml
          subPath: services.yaml
        - name: config
          mountPath: /app/config/settings.yaml
          subPath: settings.yaml
        - name: config
          mountPath: /app/config/widgets.yaml
          subPath: widgets.yaml
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: homepage-config
