apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: misc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      initContainers:
      - name: init-homepage
        image: busybox:1.35
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "mkdir -p /app/config"]
      containers:
      - image: ghcr.io/gethomepage/homepage:v1
        name: homepage
        imagePullPolicy: IfNotPresent
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: homepage.${DOMAIN}
        ports:
        - containerPort: 3000
          name: web
          protocol: TCP
        lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r -L /tmp/config/* /app/config/; chown -R 1000 /app/config"]
        volumeMounts:
        - name: config
          mountPath: /tmp/config
      restartPolicy: Always
      volumes:
      - name: config
        configMap:
          name: homepage-config
