apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: misc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: homepage
    spec:
      serviceAccountName: homepage
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      initContainers:
      containers:
      - image: ghcr.io/gethomepage/homepage:v1
        name: homepage
        imagePullPolicy: IfNotPresent
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: homepage.${DOMAIN}
        - name: HOMEPAGE_VAR_JELLYFIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: homepage-secrets
              key: jellyfin_api_key
        ports:
        - containerPort: 3000
          name: web
          protocol: TCP
        lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r -L /tmp/config/* /app/config/"]
        volumeMounts:
        - name: config
          mountPath: /app/config
        - name: tmp-config
          mountPath: /tmp/config
      restartPolicy: Always
      volumes:
      - name: config
        emptyDir: {}
      - name: tmp-config
        configMap:
          name: homepage-config
