#!/bin/bash

set -eu

dry_run_mode="none"

while getopts "d" flag; do
    case $flag in
    d)
        echo "Running dry-run mode..."
        dry_run_mode="server"
        ;;
    \?)
        echo "Wrong argument"
        exit 1
        ;;
    esac
done

project_path="$(git rev-parse --show-toplevel)"

# Deploy common resources
echo -e "\nDeploying common resources..."
common_dir="${project_path}/common"

# Deploy namespace
kubectl apply -f "${common_dir}"/00-namespace.yaml

kubectl apply -f "${common_dir}" --dry-run="${dry_run_mode}"
echo -e "Done!\n"

# Heimdall
echo -e "\nDeploying Heimdall..."
heimdall_dir="${project_path}/heimdall"

# Replace env variables
envsubst <"${heimdall_dir}"/00-deployment.yaml | sponge "${heimdall_dir}"/00-deployment.yaml
envsubst <"${heimdall_dir}"/02-ingress-route.yaml | sponge "${heimdall_dir}"/02-ingress-route.yaml

kubectl apply -f "${heimdall_dir}" --dry-run="${dry_run_mode}"
echo -e "Done!\n"

# Orcaslicer
echo -e "\nDeploying Orcaslicer..."
orcaslicer_dir="${project_path}/orcaslicer"

# Replace env variables
envsubst <"${orcaslicer_dir}"/01-deployment.yaml | sponge "${orcaslicer_dir}"/01-deployment.yaml
envsubst <"${orcaslicer_dir}"/03-ingress-route.yaml | sponge "${orcaslicer_dir}"/03-ingress-route.yaml

kubectl apply -f "${orcaslicer_dir}" --dry-run="${dry_run_mode}"
echo -e "Done!\n"
